name: Astronomer CI - Deploy code (Multiple Branches)

on:
  push:
    branches: [dev, master]

jobs:
  dev-push:
    if: github.ref == 'refs/heads/dev'
    env:
      ## Sets DEV Deployment API key credentials as environment variables
      ASTRONOMER_KEY_ID: ${{ secrets.DEV_ASTRONOMER_KEY_ID }}
      ASTRONOMER_KEY_SECRET: ${{ secrets.DEV_ASTRONOMER_KEY_SECRET }}
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Repo
      uses: actions/checkout@v2.3.4
    - name: Create PR on Master
      uses: repo-sync/pull-request@v2
      with:
        destination_branch: "master"
        pr_title: "${{ github.event.head_commit.message }}"
        pr_body: "👑 *An automated PR*"
        pr_draft: true
        github_token: ${{ secrets.GITHUB_TOKEN }}
    - name: Create image tag
      id: image_tag
      run: echo ::set-output name=image_tag::astro-$(date +%Y%m%d%H%M%S)
    - name: Build image
      uses: docker/build-push-action@v2
      with:
        tags: ${{ steps.image_tag.outputs.image_tag }}
        load: true
        build-args: |
          PIP_EXTRA_INDEX_URL=git+https://${{ secrets.PAT }}@github.com/astronomer/cse-private-packages.git
    - name: Deploy to Astro
      run: |
        curl -sSL install.astronomer.io | sudo bash -s
        astro deploy ${{ secrets.DEV_ASTRONOMER_DEPLOYMENT_ID }} --image-name ${{ steps.image_tag.outputs.image_tag }} -f
  prod-push:
    if: github.ref == 'refs/heads/master'
    env:
      ## Sets PROD Deployment API key credentials as environment variables
      ASTRONOMER_KEY_ID: ${{ secrets.ASTRONOMER_KEY_ID }}
      ASTRONOMER_KEY_SECRET: ${{ secrets.ASTRONOMER_KEY_SECRET }}
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Repo
      uses: actions/checkout@v2.3.4
    - name: Create image tag
      id: image_tag
      run: echo ::set-output name=image_tag::astro-$(date +%Y%m%d%H%M%S)
    - name: Build image
      uses: docker/build-push-action@v2
      with:
        tags: ${{ steps.image_tag.outputs.image_tag }}
        load: true
        build-args: |
          PIP_EXTRA_INDEX_URL=git+https://${{ secrets.PAT }}@github.com/astronomer/cse-private-packages.git
    - name: Deploy to Astro
      run: |
        curl -sSL install.astronomer.io | sudo bash -s
        astro deploy ${{ secrets.ASTRONOMER_DEPLOYMENT_ID }} --image-name ${{ steps.image_tag.outputs.image_tag }} -f
