name: Astronomer CI - Deploy code (Multiple Branches)

on:
  push:
    branches: [dev, master]

jobs:
  dev-push:
    if: github.ref == 'refs/heads/dev'
    env:
      ## Sets DEV Deployment API key credentials as environment variables
      ASTRONOMER_KEY_ID: ${{ secrets.DEV_ASTRONOMER_KEY_ID }}
      ASTRONOMER_KEY_SECRET: ${{ secrets.DEV_ASTRONOMER_KEY_SECRET }}
    runs-on: ubuntu-latest
    steps:
    - name: checkout repo
      uses: actions/checkout@v2.3.4
    - name: Open PR on master
      uses: repo-sync/pull-request@v2
      with:
        destination_branch: "master",
        github_token: ${{ secrets.GITHUB_TOKEN }}
        pr_label: "feature, automated pr"
        pr_title: "[Example] Simple demo"
    - name: Deploy to Astro
      run: |
        curl -sSL install.astronomer.io | sudo bash -s
        astro deploy ${{ secrets.DEV_ASTRONOMER_DEPLOYMENT_ID }}
  prod-push:
    if: github.ref == 'refs/heads/master'
    env:
      ## Sets PROD Deployment API key credentials as environment variables
      ASTRONOMER_KEY_ID: ${{ secrets.ASTRONOMER_KEY_ID }}
      ASTRONOMER_KEY_SECRET: ${{ secrets.ASTRONOMER_KEY_SECRET }}
    runs-on: ubuntu-latest
    steps:
    - name: checkout repo
      uses: actions/checkout@v2.3.4
    - name: Deploy to Astro
      run: |
        curl -sSL install.astronomer.io | sudo bash -s
        astro deploy ${{ secrets.ASTRONOMER_DEPLOYMENT_ID }}

